sudo: required

services:
    - docker


before_install:
    - docker build -t sgm/nest .

script:
    - docker run sgm/nest npm test

after_sucess:
    -echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin